//CONTACT TYPES
export const GET_CONTACTS = "GET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const CONTACTS_LOADING = "CONTACTS_LOADING";
export const LOGOUT_CONTACTS = "LOGOUT_CONTACTS";
export const FAVORITE_CONTACT = "FAVORITE_CONTACT";
export const SEARCH_CONTACT = "SEARCH_CONTACT";

//USER TYPES
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_AUTH = "SET_AUTH";
export const ADD_USER_IMAGE = "ADD_USER_IMAGE";
export const GET_USER_IMAGE = "GET_USER_IMAGE";
export const USER_IMAGE_LOADING = "USER_IMAGE_LOADING";

//LABELS
export const ADD_LABEL = "ADD_LABEL";
export const GET_LABELS = "GET_LABELS";
export const SET_LABEL = "SET_LABEL";
export const DELETE_LABEL = "DELETE_LABEL";
